config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }

  get 'pages/show'
  get 'cart/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Root
  root "books#index"

  # Books
  resources :books, only: %i[index show] do
    collection do
      get "search"
    end
  end

  # Cart
  get "/cart", to: "cart#index", as: "cart"
  post "books/add_to_cart", to: "books#add_to_cart", as: "add_to_cart"
  post 'books/update_quantity', to: 'books#update_quantity', as: 'update_quantity'
  delete "books/remove_from_cart", to: "books#remove_from_cart", as: "remove_from_cart"

  # Checkout
  scope '/cart' do
    get 'checkout', to: 'checkout#index', as: 'checkout'
  end

  scope '/checkout' do
    post 'create',      to: 'checkout#create',      as: 'checkout_create'
    get  'cancel',      to: 'checkout#cancel',      as: 'checkout_cancel'
    get  'pre_success', to: 'checkout#pre_success', as: 'checkout_pre_success'
    get  'success',     to: 'checkout#success',     as: 'checkout_success'
    post 'update_user_address', to: 'checkout#update_user_address'
  end

  # Categories
  get "/categories", to: "categories#index"
  get "/categories/:category_name", to: "categories#show"

  # About & Contact pages
  get "pages/:slug", to: 'pages#show', as: 'regular_page'

  # Users
  resource :user, only: [:update]

  resources :users do
    resources :orders, only: %i[index show create]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors, dependent: :destroy
  has_many :books, through: :book_authors

  validates :name, presence: true, uniqueness: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher, optional: true, inverse_of: :books

  has_many :book_categories, dependent: :destroy
  has_many :categories, through: :book_categories

  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors

  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews

  has_many :book_orders
  has_many :orders, through: :book_orders

  accepts_nested_attributes_for :book_categories, allow_destroy: true
  accepts_nested_attributes_for :book_authors, allow_destroy: true

  has_one_attached :image

  validates :title, presence: true
  validates :published_date, :description, :isbn, :page_count, :language, presence:  true,
                                                                          allow_nil: false

  # Validation for uniqueness of ISBN
  validates :isbn, uniqueness: true, allow_nil: false

  # Validation for numericality of page_count
  validates :page_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 },
                         allow_nil:    true

  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :is_on_sale, inclusion: { in: [true, false] }
  validates :sale_price, numericality: { greater_than_or_equal_to: 0 }, if: :is_on_sale?

  def average_rating
    format("%.1f", reviews.average(:rating).to_f)
  end
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author

  validates :book_id,
            uniqueness: { scope:   :author_id,
                          message: "This author has already been added to this book" }
end

app/models/book_category.rb
class BookCategory < ApplicationRecord
  belongs_to :book
  belongs_to :category

  validates :book_id,
            uniqueness: { scope:   :category_id,
                          message: "This category has already been added to this book" }
end

app/models/book_order.rb
class BookOrder < ApplicationRecord
  belongs_to :order
  belongs_to :book

  validates :book_id, presence: true
  validates :order_id, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :purchase_price, presence: true, numericality: { greater_than: 0 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :book_categories, dependent: :destroy
  has_many :books, through: :book_categories

  validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :book_orders
  has_many :books, through: :book_orders

  validates :user_id, presence: true
  validates :subtotal, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :purchase_gst, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :purchase_pst, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :purchase_hst, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :status, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :content, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users

  validates :name, presence: true, length: { maximum: 30 }
  validates :name_abbreviation, presence: true, length: { maximum: 2 }
  validates :gst, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :pst, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :hst, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books

  validates :name, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :book_id, :user_id, :rating, presence: true
  validates :rating, numericality: {
    only_integer:             true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to:    5
  }

  validates :book_id,
            uniqueness: { scope: :user_id, message: "Has already been rated by this user" }

  validate :rating_comment_length

  # Custom validation method to check the length of the comment
  def rating_comment_length
    return unless comment.present? && comment.length > 500

    errors.add(:comment, "comment is too long (maximum is 500 characters)")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  belongs_to :province, optional: true
  has_many :reviews
  has_many :books, through: :reviews
  has_many :orders
  has_many :book_orders, through: :orders

  validates :username, :email, :first_name, :last_name, presence: true
  validates :username, :email, uniqueness: true

  # Validation for username format (alphanumeric characters, underscores, and dashes)
  validates :username,
            format: { with:    /\A[a-zA-Z0-9_.-]+\z/,
                      message: " Username can only contain letters, numbers, underscores, and dashes" }

  # Validation for email format
  validates :email,
            format: { with:    /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
                      message: "Must be a valid email address" }

  # Password validations
  validates :password, presence: true, length: { minimum: 8 }
  validates :password, confirmation: true, unless: -> { password.blank? }

  # Validation for length (assuming minimum and maximum lengths) of attribures.
  validates :username, length: { minimum: 3, maximum: 30 }
  validates :first_name, :last_name, length: { maximum: 50 }
  validates :address, length: { maximum: 100 }
  validates :city, length: { maximum: 60 }

  # Validation for postal code format
  validates :postal_code,
            format: { with: /\A[ABCEGHJKLMNPRSTVXY]\d[ABCEGHJKLMNPRSTVWXYZ] ?\d[ABCEGHJKLMNPRSTVWXYZ]\d\z/i },
            allow_nil: true,
            allow_blank: true
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index

  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cart/checkout.html.erb
<div class="container pt-4">
  <%= link_to "↩ Return to Cart", cart_path %>
  <h1 class="title mt-2">Checkout</h1>
  <%# Empty state %>
  <% if @cart.empty? %>
    <div class="notification is-danger is-light pb-5">
      Your cart is empty
    </div>
    <%= link_to root_path, class: "button is-link mt-3 mb-4" do %>
      Return Home
    <% end %>
  <% else %>
    <div class="columns">
      <div class="column">
        <%= render partial: "layouts/components/shipping_details" %>
        <%= render partial: "layouts/components/cart_summary" %>
      </div>
      <div class="column is-one-fifth">
        <div class="purchase-info-container p-4">
          <div class="is-flex is-justify-content-space-between is-align-items-baseline">
            <div class="is-size-6">Subtotal (<%= pluralize(@cart_item_count, 'item') %>)</div>
            <div class="is-size-6 has-text-weight-bold"><%= number_to_currency @cart_subtotal, unit: "$" %></div>
          </div>
          <div class="is-flex is-justify-content-space-between is-align-items-baseline">
            <div class="is-size-6">PST (<%= number_to_percentage(@province.pst * 100, precision: 0) %>)</div>
            <div class="is-size-6 has-text-weight-bold"><%= number_to_currency @total_pst, unit: "$" %></div>
          </div>
          <div class="is-flex is-justify-content-space-between is-align-items-baseline">
            <div class="is-size-6">GST (<%= number_to_percentage(@province.gst * 100, precision: 0) %>)</div>
            <div class="is-size-6 has-text-weight-bold"><%= number_to_currency @total_gst, unit: "$" %></div>
          </div>
          <div class="is-flex is-justify-content-space-between is-align-items-baseline">
            <div class="is-size-6">HST (<%= number_to_percentage(@province.hst * 100, precision: 0) %>)</div>
            <div class="is-size-6 has-text-weight-bold"><%= number_to_currency @total_hst, unit: "$" %></div>
          </div>
          <div class="is-flex is-justify-content-space-between is-align-items-baseline">
            <div class="is-size-6">Shipping</div>
            <div class="is-size-6 has-text-weight-bold">FREE</div>
          </div>
          <hr class="my-4" style="height:1px;border-width:0;color:#bcbec6;background-color:#bcbec6">
          <div class="is-flex is-justify-content-space-between is-align-items-baseline">
            <div class="is-size-4">Total</div>
            <div class="is-size-4 has-text-danger-dark"><%= number_to_currency @cart_total, unit: "$" %></div>
          </div>
          <%= button_to "Proceed to Payment", checkout_create_path, remote: true, data: { 'turbo': 'false' }, class: "button is-fullwidth is-link is-warning mt-4" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/cart/index.html.erb
<section class = "section">
  <div class="container">
    <h1 class="title">Shopping Cart</h1>
    <% if @cart.empty? %>
      <div class="notification is-link is-light has-text-centered pb-5">
        <span class="" style="font-size: 4rem;">
          <i class="fa-regular fa-paper-plane"></i>
        </span>
        <p class="is-size-5 has-text-weight-medium">Your cart is empty</p>
        <p class="is-size-6">Looks like you haven't added any books to your cart yet.</p>
        <%= link_to root_path, class: "button is-link mt-3 mb-4" do %>
          Return Home
        <% end %>
      </div>
    <% else %>
      <div class="columns">
        <div class="column">
          <% @cart.each do |item| %>
            <%= render partial: "layouts/components/cart_item", locals: { item: item } %>
          <% end %>
          <div class="is-flex is-justify-content-end is-align-items-baseline">
            <div class="has-text-weight-bold is-size-5 pr-4 ">Subtotal (<%= pluralize(@cart_item_count, 'item') %>):</div>
            <div class="is-size-4 has-text-danger-dark"><%= number_to_currency @cart_subtotal, unit: "$" %></div>
          </div>
        </div>
        <div class="column is-one-fifth">
          <div class="purchase-info-container p-4">
            <div class="is-flex is-justify-content-space-between is-align-items-baseline">
              <div class="is-size-6">Subtotal (<%= pluralize(@cart_item_count, 'item') %>):</div>
              <div class="is-size-6 has-text-weight-bold"><%= number_to_currency @cart_subtotal, unit: "$" %></div>
            </div>
            <%= link_to checkout_path, class: "button is-fullwidth is-link is-warning mt-4" do %>
              Proceed to Checkout
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>