config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }

  get 'pages/show'
  get 'cart/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Root
  root "books#index"

  # Books
  resources :books, only: %i[index show] do
    collection do
      get "search"
    end
  end

  # Cart
  get "/cart", to: "cart#index", as: "cart"
  post "books/add_to_cart", to: "books#add_to_cart", as: "add_to_cart"
  post 'books/update_quantity', to: 'books#update_quantity', as: 'update_quantity'
  delete "books/remove_from_cart", to: "books#remove_from_cart", as: "remove_from_cart"

  # Checkout
  scope '/cart' do
    get 'checkout', to: 'checkout#index', as: 'checkout'
  end

  scope '/checkout' do
    post 'create',      to: 'checkout#create',      as: 'checkout_create'
    get  'cancel',      to: 'checkout#cancel',      as: 'checkout_cancel'
    get  'pre_success', to: 'checkout#pre_success', as: 'checkout_pre_success'
    get  'success',     to: 'checkout#success',     as: 'checkout_success'
    post 'update_user_address', to: 'checkout#update_user_address'
  end

  # Categories
  get "/categories", to: "categories#index"
  get "/categories/:category_name", to: "categories#show"

  # About & Contact pages
  get "pages/:slug", to: 'pages#show', as: 'regular_page'

  # Users
  resource :user, only: [:update]

  resources :users do
    resources :orders, only: %i[index show create]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :book_orders
  has_many :books, through: :book_orders

  validates :user_id, presence: true
  validates :subtotal, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :purchase_gst, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :purchase_pst, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :purchase_hst, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :status, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  # All orders of the current user
  def index
    @user = current_user
    @orders = @user.orders.includes(book_orders: :book).order(created_at: :desc).all

    if @orders.empty?
      flash.now[:alert] = "No orders found for #{current_user.username} yet"
    end
  end

  # Details about the order
  def show
    @user = current_user
    @order = @user.orders.find(params[:id])
    @book_orders = @order.book_orders.includes(:book)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Your Orders <%= current_user.username %></h1>

    <% if @orders.present? %>
      <% @orders.each do |order| %>
        <div class="box">
          <div class="is-flex is-justify-content-space-between">
            <p class="title is-4 mb-5">Order #<%= order.id %> from <%= order.created_at.strftime('%Y-%m-%d') %></p>
            <%= link_to "View Details", user_order_path(current_user, order), class: "button is-info" %>
          </div>
          <% order.book_orders.each do |book_order| %>
            <div class="media mb-0">
              <div class="media-left">
                <% if book_order.book.image.present? %>
                  <%= image_tag(book_order.book.image.variant(resize_to_limit: [30, 30]), alt: book_order.book.title) %>
                <% elsif book_order.book.image_thumbnail.present? %>
                  <%= image_tag(book_order.book.image_thumbnail, size: "30x30", alt: book_order.book.title) %>
                <% end %>
              </div>
              <div class="media-content">
                <p class="title is-6"><%= book_order.book.title %></p>
                <p class="subtitle is-6"> Quanity: <%= book_order.quantity %>, Price: <b>$<%= book_order.purchase_price %></b> </p>
              </div>
            </div>
          <% end %>
       </div>
      <% end %>
    <% else %>
      <% if flash[:alert].present? %>
        <p class="subtitle">No orders yet.</p>
          <script>
          setTimeout(function() {
            window.location.href = '<%= root_path %>';
          }, 3000);
        </script>
      <% end %>
    <% end %>
  </div>
</section>

app/views/orders/show.html.erb
<div class="container pt-4">
  <%= link_to "↩ Return to Orders", user_orders_path %>
  <% if @order %>
    <h1 class="title mt-2">Order # <%= @order.id %> from <%= @order.created_at.strftime('%Y-%m-%d') %> </h1>
      <div class="columns">
        <div class="column">
          <%= render partial: "layouts/components/order_address" %>
          <%= render partial: "layouts/components/order_summary" %>
        </div>
        <div class="column is-one-fifth">
          <%= render partial: "layouts/components/order_total" %>
        </div>
      </div>
  <% end %>
</div>