config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }

  get 'pages/show'
  get 'cart/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Root
  root "books#index"

  # Books
  resources :books, only: %i[index show] do
    collection do
      get "search"
    end
  end

  # Cart
  get "/cart", to: "cart#index", as: "cart"
  post "books/add_to_cart", to: "books#add_to_cart", as: "add_to_cart"
  post 'books/update_quantity', to: 'books#update_quantity', as: 'update_quantity'
  delete "books/remove_from_cart", to: "books#remove_from_cart", as: "remove_from_cart"

  # Checkout
  scope '/cart' do
    get 'checkout', to: 'checkout#index', as: 'checkout'
  end

  scope '/checkout' do
    post 'create',      to: 'checkout#create',      as: 'checkout_create'
    get  'cancel',      to: 'checkout#cancel',      as: 'checkout_cancel'
    get  'pre_success', to: 'checkout#pre_success', as: 'checkout_pre_success'
    get  'success',     to: 'checkout#success',     as: 'checkout_success'
    post 'update_user_address', to: 'checkout#update_user_address'
  end

  # Categories
  get "/categories", to: "categories#index"
  get "/categories/:category_name", to: "categories#show"

  # About & Contact pages
  get "pages/:slug", to: 'pages#show', as: 'regular_page'

  # Users
  resource :user, only: [:update]

  resources :users do
    resources :orders, only: %i[index show create]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher, optional: true, inverse_of: :books

  has_many :book_categories, dependent: :destroy
  has_many :categories, through: :book_categories

  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors

  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews

  has_many :book_orders
  has_many :orders, through: :book_orders

  accepts_nested_attributes_for :book_categories, allow_destroy: true
  accepts_nested_attributes_for :book_authors, allow_destroy: true

  has_one_attached :image

  validates :title, presence: true
  validates :published_date, :description, :isbn, :page_count, :language, presence:  true,
                                                                          allow_nil: false

  # Validation for uniqueness of ISBN
  validates :isbn, uniqueness: true, allow_nil: false

  # Validation for numericality of page_count
  validates :page_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 },
                         allow_nil:    true

  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :is_on_sale, inclusion: { in: [true, false] }
  validates :sale_price, numericality: { greater_than_or_equal_to: 0 }, if: :is_on_sale?

  def average_rating
    format("%.1f", reviews.average(:rating).to_f)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.page(params[:page]).per(20)
    apply_filters
  end

  def show
    @book = Book.find(params[:id])
    @reviews = @book.reviews
  end

  def search
    @categories = @all_categories
    keywords = params[:keywords]
    category_id = params[:category_id]

    @books = Book.all

    if keywords.present?
      @books = @books.where("title LIKE ? OR description LIKE ?", "%#{keywords}%", "%#{keywords}%")
    end

    if category_id.present?
      @books = @books.joins(:categories).where(book_categories: { category_id: category_id })
    end

    @books = @books.page(params[:page]).per(20)
  end

  def add_to_cart
    id = params[:id].to_i
    quantity = params[:quantity].to_i

    # Look for an element matching the id.
    # If there is a match, add to the quantity.
    # Otherwise, set the quantity.
    book = @cart.find { |book_order| book_order["id"] == id }

    if book
      book["quantity"] += quantity
    else
      @cart << { id:, quantity: }
    end

    redirect_to cart_path
  end

  def update_quantity
    id = params[:id].to_i
    quantity = params[:quantity].to_i

    book = @cart.find { |book_order| book_order["id"] == id }

    if book
      book["quantity"] = quantity
    end

    redirect_to cart_path
  end

  def remove_from_cart
    id = params[:id].to_i
    quantity = params[:quantity].to_i

    # Look for an element matching the id.
    # If there is a match, subtract from the quantity.
    # If result is less than or equals to zero, delete the item from the cart.
    book = @cart.find { |book_order| book_order["id"] == id }

    if book
      book["quantity"] -= quantity

      if book["quantity"] <= 0
        @cart.delete_if { |book_order| book_order["id"] == id }
      end
    end

    redirect_to cart_path
  end

  #
  def apply_filters
    filter_conditions = []

    if params[:on_sale].present?
      filter_conditions << { is_on_sale: true }
    end

    if params[:new].present?
      filter_conditions << ['books.created_at >= ?', 3.days.ago]
    end

    if params[:recently_updated].present?
      # Filter based on recently updated, excluding new products
      filter_conditions << ['books.updated_at >= ? AND books.created_at < ?', 3.days.ago, 3.days.ago]
    end


    # Apply all filter conditions to @books
    filter_conditions.each do |condition|
      if condition.is_a?(Hash)
        @books = @books.where(condition)
      else
        @books = @books.where(*condition)
      end
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<%= link_to book do %>
  <div class="column is-one-fifth">
    <div class="card book-card">
      <div class="card-image">
        <figure class="image">
          <% if book.is_on_sale? %>
            <div class="book-sale-tag"><%= number_to_percentage((-100 * (1 - book.sale_price / book.price)), precision: 0) %></div>
          <% end %>
          <% if book.image.present? %>
            <%=  image_tag(book.image.variant(resize_to_limit: [300, 300]), alt: book.title ) %>
          <% elsif book.image_thumbnail.present? %>
            <%= image_tag(book.image_thumbnail, size: "300x300", alt: book.title) %>
          <% end %>
        </figure>
      </div>
      <div class="card-content px-0">
        <div class="content">
          <p class="book-title is-6 pb-1 m-0"><%= book.title %></p>
          <p class="book-authors mb-2"><%= book.authors.map{ |author| author.name }.join(", ") %></p>
          <%# Price %>
          <div class="is-flex is-justify-content-space-between mb-3 is-align-content-end">
            <% if book.sale_price.present? && book.is_on_sale %>
              <span class="book-price book-sale-price"><%= number_to_currency(book.sale_price, unit: "$") %></span>
            <% end %>
            <% if book.price.present? %>
              <span class="book-price book-regular-price <%= book.is_on_sale? ? "is-on-sale" : "" %>"><%= number_to_currency(book.price, unit: "$") %></span>
            <% end %>
          </div>
          <%# Rating %>
          <div class="book-rating mb-2">
            <%# Full stars %>
            <% Integer(Float(book.average_rating).floor()).times do %>
              <i class="fas fa-solid fa-star has-text-warning"></i>
            <% end %>
            <%# Half star %>
            <% if (Float(book.average_rating).round(1) % 1 >= 0.5) %>
              <i class="fas fa-solid fa-star-half-stroke has-text-warning"></i>
            <% elsif (Integer(Float(book.average_rating).floor()) != 5) %>
              <i class="fas fa-regular fa-star has-text-grey-lighter"></i>
            <% end %>
            <%# Empty stars %>
            <% (4 - Integer(Float(book.average_rating).floor())).times do %>
              <i class="fas fa-regular fa-star has-text-grey-lighter"></i>
            <% end %>
            <span class="review-count ml-2"><%= pluralize book.reviews.count, "review" %></span>
          </div>
          <% book.categories.each do |category| %>
            <%= link_to "/categories/#{category.name}" do %>
              <span class="tag is-link is-light is-small"><%= category.name.gsub("_", " ").gsub("-", ",") %></span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/books/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns mt-1">
      <div class="column is-one-fifth">
        <%= render partial: "layouts/components/categories_side_bar" %>
      </div>
      <div class="column is-four-fifths">
        <div class="is-flex is-justify-content-space-between mb-5">
          <h1 class="title">Books</h1>
        </div>
        <div class="columns is-multiline">
          <%= render @books %>
        </div>
        <%= paginate @books %>
      </div>
    </div>
  </div>
</section>

app/views/books/search.html.erb
<section class="section">
  <div class="container">
    <h2 class="title is-size-3 mt-2 mb-5">Search results</h2>
      <p class="subtitle">
        <%= pluralize @books.total_count, "book"%> found
        <% if (params[:keywords] != "") %>
          for "<strong><%= params[:keywords]%></strong>"
        <% end %>
        <% if (params[:category_id] != "") %>
          in "<strong><%= @categories.find_by(id: params[:category_id]).name.gsub("_", " ").gsub("-", ",") %></strong>"
        <% end %>
      </p>
     <div class="columns is-multiline">
        <%= render @books %>
      </div>
    <%= paginate @books %>
  </div>
</section>

app/views/books/show.html.erb
<% content_for(:html_title){@book.title}%>
<div class="container">
  <%# Breadcrumb %>
  <nav class="breadcrumb mt-4 mb-8" aria-label="breadcrumbs">
    <ul>
      <li><%= link_to "Books", books_path %></li>
      <li><%= link_to "Categories", categories_path %></li>
      <% if(@book.categories.any?) %>
        <li><%= link_to @book.categories.first.name.gsub("_", " ").gsub("-", ","), "/categories/#{@book.categories.first.name}" %></li>
      <% end %>
    </ul>
  </nav>
  <%# Image and description %>
  <div class="columns">
    <%# Book cover %>
    <div class="column is-one-fifth">
      <figure class="image">
        <% if @book.is_on_sale? %>
          <div class="book-sale-tag"><%= number_to_percentage((-100 * (1 - @book.sale_price / @book.price)), precision: 0) %></div>
        <% end %>
        <% if @book.image.present? %>
          <%= image_tag(@book.image) %>
        <% else %>
          <%= image_tag(@book.image_thumbnail, alt: @book.title) %>
        <% end %>
      </figure>
      <%= link_to @book.preview_link, target: "_blank", class: "button is-fullwidth is-link is-outlined mt-4" do %>
        <span class="icon" style="opacity: 0.8;">
          <i class="fa-brands fa-readme mr-0"></i>
        </span>
        <span class="pl-2">Preview</span>
      <% end %>
    </div>
    <%# Title, authors, categories, description %>
    <div class ="column">
      <div class="is-flex is-justify-content-space-between mb-3">
        <%# Title and subtitle %>
        <div>
          <h1 class="title has-text-info"><%= @book.title %></h1>
          <h2 class="subtitle is-6">By <%= @book.authors.map{ |author| author.name }.join(", ") %></h2>
        </div>
      </div>
      <%# Rating %>
      <div>
        <div class ="is-flex mb-2">
          <span class="mr-2"><strong><%= Float(@book.average_rating).round(1) %></strong></span>
          <div>
            <%# Full stars %>
            <% Integer(Float(@book.average_rating).floor()).times do %>
              <i class="fas fa-solid fa-star has-text-warning"></i>
            <% end %>
            <%# Half star %>
            <% if (Float(@book.average_rating).round(1) % 1 >= 0.5) %>
              <i class="fas fa-solid fa-star-half-stroke has-text-warning"></i>
            <% elsif (Integer(Float(@book.average_rating).floor()) != 5) %>
              <i class="fas fa-regular fa-star has-text-grey-lighter"></i>
            <% end %>
            <%# Empty stars %>
            <% (4 - Integer(Float(@book.average_rating).floor())).times do %>
              <i class="fas fa-regular fa-star has-text-grey-lighter"></i>
            <% end %>
          </div>
          <span class="ml-3"><%= pluralize @book.reviews.count, "review" %></span>
        </div>
      </div>
      <%# Categories %>
      <h3 class="is-size-7 mb-6">
        <% if(@book.categories.any?) %>
          <span class="mr-2 has-text-primary"><strong>CATEGORIES</strong></span>
          <% @book.categories.each do |category| %>
            <%= link_to "/categories/#{category.name}" do %>
              <span class="tag is-link is-light is-medium"><%= category.name.gsub("_", " ").gsub("-", ",") %></span>
            <% end %>
          <% end %>
        <% end %>
      </h3>
      <p class="is-size-6"><%= @book.description %></p>
    </div>
    <%# Rating, Price, Purchase actions %>
    <div class="column is-one-fifth">
      <div class="purchase-info-container p-4">

        <div class="has-text-right mb-6">
          <%# Price %>
          <div class="is-flex is-justify-content-space-between is-align-items-baseline">
            <div class="has-text-weight-bold is-size-6">Buy new:</div>
            <div class="book-price is-size-4 has-text-danger-dark">
              <% if @book.sale_price.present? && @book.is_on_sale %>
                <%= number_to_currency(@book.sale_price, unit: "$") %>
              <% else %>
                <%= number_to_currency(@book.price, unit: "$") %>
              <% end %>
            </div>
          </div>

          <%# List price and discount %>
          <div class="is-size-7">
            <% if @book.sale_price.present? && @book.is_on_sale %>
                <p>List price: <s class="has-text-grey"><%= number_to_currency(@book.price, unit: "$") %></s></p>
                <p>Save: <%= number_to_currency(@book.price - @book.sale_price, unit: "$") %> (<%= number_to_percentage((-100 * (1 - @book.sale_price / @book.price)), precision: 0) %>)</p>
            <% end %>
          </div>
        </div>
        <p class="is-size-5 has-text-success-dark mb-1">In Stock</p>
        <%= form_tag add_to_cart_path, method: :post do %>
          <div class="is-flex">
            <p class="pt-1">Quantity</p>
            <%= select_tag :quantity, options_for_select(1..10), class: "select ml-2" %>
          </div>
          <%= hidden_field_tag :id, @book.id %>
          <%= submit_tag "Add to cart", class: "button is-fullwidth is-warning mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
  <%# Book details %>
  <div class = "columns is-centered is-vcentered mt-5">
    <%# Publisher %>
    <div class ="column is-one-fifth has-text-centered">
      <div class="icon is-medium has-text-info">
        <i class="fas fa-2x pb-3 fa-solid fa-house"></i>
      </div>
      <p class = "is-size-6"> <%= @book.publisher.name %></p>
    </div>
    <%# Published date %>
    <div class ="column is-one-fifth has-text-centered">
      <div class="icon is-medium has-text-info">
        <i class="fas fa-2x pb-3 fa-solid fa-calendar-days"></i>
      </div>
      <p class = "is-size-6"> <%= @book.published_date %></p>
    </div>
    <%# ISBN %>
    <div class ="column is-one-fifth has-text-centered">
      <div class="icon is-medium has-text-info">
        <i class=" fas fa-2x pb-3 fa-solid fa-barcode"></i>
      </div>
      <p class = "is-size-6"> <%= @book.isbn %></p>
    </div>
    <%# Page count %>
    <div class ="column is-one-fifth has-text-centered">
      <div class="icon is-medium has-text-info">
        <i class=" fas fa-2x pb-3 fa-solid fa-book-open"></i>
      </div>
      <p class = "is-size-6"> <%= @book.page_count %> pages</p>
    </div>
    <%# Language %>
    <div class="column is-one-fifth has-text-centered">
      <div class="icon is-medium has-text-info">
        <i class="fas fa-2x pb-3 fa-language"></i>
      </div>
      <p class="is-size-6"><%= @book.language == "en" ? "English" : @book.language %></p>
    </div>
  </div>
  <%# Reviews %>
  <% if (@book.reviews.count == 0 )%>
    <article class="message is-warning">
      <div class="message-body">
        There are currently no reviews for this book.
      </div>
    </article>
  <% else %>
    <details>
      <summary class="is-size-5 has-text-weight-bold">
        User reviews (<%= @book.reviews.count %>)
      </summary>
      <%# List of reviews %>
      <ul>
        <% @book.reviews.each do |review| %>
          <li>
            <div class="box mt-5">
              <div class="is-flex is-justify-content-space-between">
                <span class="icon-text">
                  <span class="icon has-text-info icon is-large">
                    <i class=" fas fa-2x fa-solid fa-user"></i>
                  </span>
                  <div>
                    <span class ="is-size-5"><%= review.user.username %></span>
                    <p class ="mb-3">Reviewed on <%= review.created_at.strftime("%d/%m/%Y, %H:%M:%S") %></p>
                  </div>
                </span>
                <%# Rating %>
                <div>
                  <div class ="has-text-centered mb-2">
                    <span>Rating <strong><%= Float(review.rating) %></strong></span>
                    <div class="ml-1">
                      <%# Full stars %>
                      <% Integer(Float(review.rating).floor()).times do %>
                        <i class="fas fa-solid fa-star has-text-warning"></i>
                      <% end %>
                      <%# Empty stars %>
                      <% (5 - Integer(Float(review.rating).floor())).times do %>
                        <i class="fas fa-regular fa-star has-text-grey-lighter"></i>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <p class ="is-size-5"><%= review.comment %></p>
            </div>
          </li>
        <% end %>
      </ul>
    </details>
  <% end %>
</div>