config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }

  get 'pages/show'
  get 'cart/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Root
  root "books#index"

  # Books
  resources :books, only: %i[index show] do
    collection do
      get "search"
    end
  end

  # Cart
  get "/cart", to: "cart#index", as: "cart"
  post "books/add_to_cart", to: "books#add_to_cart", as: "add_to_cart"
  post 'books/update_quantity', to: 'books#update_quantity', as: 'update_quantity'
  delete "books/remove_from_cart", to: "books#remove_from_cart", as: "remove_from_cart"

  # Checkout
  scope '/cart' do
    get 'checkout', to: 'checkout#index', as: 'checkout'
  end

  scope '/checkout' do
    post 'create',      to: 'checkout#create',      as: 'checkout_create'
    get  'cancel',      to: 'checkout#cancel',      as: 'checkout_cancel'
    get  'pre_success', to: 'checkout#pre_success', as: 'checkout_pre_success'
    get  'success',     to: 'checkout#success',     as: 'checkout_success'
    post 'update_user_address', to: 'checkout#update_user_address'
  end

  # Categories
  get "/categories", to: "categories#index"
  get "/categories/:category_name", to: "categories#show"

  # About & Contact pages
  get "pages/:slug", to: 'pages#show', as: 'regular_page'

  # Users
  resource :user, only: [:update]

  resources :users do
    resources :orders, only: %i[index show create]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors, dependent: :destroy
  has_many :books, through: :book_authors

  validates :name, presence: true, uniqueness: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher, optional: true, inverse_of: :books

  has_many :book_categories, dependent: :destroy
  has_many :categories, through: :book_categories

  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors

  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews

  has_many :book_orders
  has_many :orders, through: :book_orders

  accepts_nested_attributes_for :book_categories, allow_destroy: true
  accepts_nested_attributes_for :book_authors, allow_destroy: true

  has_one_attached :image

  validates :title, presence: true
  validates :published_date, :description, :isbn, :page_count, :language, presence:  true,
                                                                          allow_nil: false

  # Validation for uniqueness of ISBN
  validates :isbn, uniqueness: true, allow_nil: false

  # Validation for numericality of page_count
  validates :page_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 },
                         allow_nil:    true

  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :is_on_sale, inclusion: { in: [true, false] }
  validates :sale_price, numericality: { greater_than_or_equal_to: 0 }, if: :is_on_sale?

  def average_rating
    format("%.1f", reviews.average(:rating).to_f)
  end
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author

  validates :book_id,
            uniqueness: { scope:   :author_id,
                          message: "This author has already been added to this book" }
end

app/models/book_category.rb
class BookCategory < ApplicationRecord
  belongs_to :book
  belongs_to :category

  validates :book_id,
            uniqueness: { scope:   :category_id,
                          message: "This category has already been added to this book" }
end

app/models/book_order.rb
class BookOrder < ApplicationRecord
  belongs_to :order
  belongs_to :book

  validates :book_id, presence: true
  validates :order_id, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :purchase_price, presence: true, numericality: { greater_than: 0 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :book_categories, dependent: :destroy
  has_many :books, through: :book_categories

  validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :book_orders
  has_many :books, through: :book_orders

  validates :user_id, presence: true
  validates :subtotal, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :purchase_gst, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :purchase_pst, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :purchase_hst, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :status, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :content, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users

  validates :name, presence: true, length: { maximum: 30 }
  validates :name_abbreviation, presence: true, length: { maximum: 2 }
  validates :gst, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :pst, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :hst, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books

  validates :name, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :book_id, :user_id, :rating, presence: true
  validates :rating, numericality: {
    only_integer:             true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to:    5
  }

  validates :book_id,
            uniqueness: { scope: :user_id, message: "Has already been rated by this user" }

  validate :rating_comment_length

  # Custom validation method to check the length of the comment
  def rating_comment_length
    return unless comment.present? && comment.length > 500

    errors.add(:comment, "comment is too long (maximum is 500 characters)")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  belongs_to :province, optional: true
  has_many :reviews
  has_many :books, through: :reviews
  has_many :orders
  has_many :book_orders, through: :orders

  validates :username, :email, :first_name, :last_name, presence: true
  validates :username, :email, uniqueness: true

  # Validation for username format (alphanumeric characters, underscores, and dashes)
  validates :username,
            format: { with:    /\A[a-zA-Z0-9_.-]+\z/,
                      message: " Username can only contain letters, numbers, underscores, and dashes" }

  # Validation for email format
  validates :email,
            format: { with:    /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
                      message: "Must be a valid email address" }

  # Password validations
  validates :password, presence: true, length: { minimum: 8 }
  validates :password, confirmation: true, unless: -> { password.blank? }

  # Validation for length (assuming minimum and maximum lengths) of attribures.
  validates :username, length: { minimum: 3, maximum: 30 }
  validates :first_name, :last_name, length: { maximum: 50 }
  validates :address, length: { maximum: 100 }
  validates :city, length: { maximum: 60 }

  # Validation for postal code format
  validates :postal_code,
            format: { with: /\A[ABCEGHJKLMNPRSTVXY]\d[ABCEGHJKLMNPRSTVWXYZ] ?\d[ABCEGHJKLMNPRSTVWXYZ]\d\z/i },
            allow_nil: true,
            allow_blank: true
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield(:html_title) + "-" if content_for(:html_title) %>BookHub Library</title>
    <%= favicon_link_tag asset_path('icon.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css">
    <script src="https://js.stripe.com/v3/"></script>
  </head>
  <body>
    <%= render partial: 'layouts/components/navbar' %>
    <%= render partial: 'layouts/components/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/components/_book_tbody.html.erb
<tr>
  <td>
    <% if book.image.present? %>
      <%=  image_tag(book.image.variant(resize_to_limit: [60, 60]), alt: book.title ) %>
    <% elsif book.image_thumbnail.present? %>
        <%= image_tag(book.image_thumbnail, size: "40x40", alt: book.title) %>
    <% else %>
    <% end %>
  </td>
  <td><%= link_to book.title, book %></td>
  <td>
  <% book.categories.each do |category| %>
    <%= link_to "/categories/#{category.name}" do %>
      <span class="tag is-link is-light is-medium"><%= category.name.gsub("_", " ").gsub("-", ",") %></span>
    <% end %>
  <% end %>
  </td>
  <td><%= book.authors.map{ |author| author.name }.join(", ") %></td>
</tr>

app/views/layouts/components/_book_thead.html.erb
<thead>
  <tr>
    <th>Cover</th>
    <th>Title</th>
    <th>Categories</th>
    <th>Authors</th>
  </tr>
</thead>

app/views/layouts/components/_cart_item.html.erb
<% book = Book.find(item["id"]) %>
<% unit_price = book.is_on_sale ? book.sale_price : book.price %>
<% total_price = unit_price * item["quantity"] %>

<div class="card mb-3">
  	<div class="card-content">
		<div class="is-flex is-justify-content-space-between">
			<div>
				<div class="media mb-0">
					<div class="media-left">
						<% if book.image.present? %>
							<%=  image_tag(book.image.variant(resize_to_limit: [30, 30]), alt: book.title ) %>
						<% elsif book.image_thumbnail.present? %>
							<%= image_tag(book.image_thumbnail, size: "30x30", alt: book.title) %>
						<% end %>
					</div>
					<div class="media-content">
						<p class="title is-5"><%= book.title %></p>
						<p class="subtitle is-6"><%= book.authors.map{ |author| author.name }.join(", ")%></p>
					</div>
				</div>
				<div class="is-flex is-align-items-baseline mt-3">
					<span class="mr-2">Quantity:</span>
					<div class="">
						<%= form_with url: update_quantity_path(id: item["id"]), method: :post, html: { class: "field has-addons" } do |form| %>
						<div class="control" style="width: 4em">
							<%= form.number_field :quantity, value: item["quantity"], min: 1, class: "input is-small" %>
						</div>
						<div class="control">
							<%= form.submit "Update", class: "button is-small is-ghost" %>
						</div>
						<% end %>
					</div>
					<%= form_tag remove_from_cart_path, method: :delete do %>
						<%= hidden_field_tag :id, item["id"] %>
						<%= hidden_field_tag :quantity, item["quantity"] %>
						<%= submit_tag "Remove", class: "button is-small is-danger is-light ml-1" %>
					<% end %>
				</div>
			</div>

			<%# Price %>
			<div class=" has-text-right">
				<p class="book-price is-size-5 has-text-weight-bold">
					<% if book.sale_price.present? && book.is_on_sale %>
						<%= number_to_currency(book.sale_price, unit: "$") %>
					<% else %>
						<%= number_to_currency(book.price, unit: "$") %>
					<% end %>
				</p>
				<%# List price and discount %>
				<div class="is-size-7">
					<% if book.sale_price.present? && book.is_on_sale %>
						<p>List price: <s class="has-text-grey"><%= number_to_currency(book.price, unit: "$") %></s></p>
						<p>Save: <%= number_to_currency(book.price - book.sale_price, unit: "$") %> (<%= number_to_percentage((-100 * (1 - book.sale_price / book.price)), precision: 0) %>)</p>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/components/_cart_summary.html.erb
<div class="card mb-3">
  <div class="card-content">
    <p class="title is-5 mb-5">Cart Summary</p>
    <% @cart.each_with_index do |item, index| %>
      <% book = Book.find(item["id"]) %>
      <% unit_price = book.is_on_sale ? book.sale_price : book.price %>
      <% total_price = unit_price * item["quantity"] %>
      <div class="is-flex is-justify-content-space-between">
        <div>
          <div class="media mb-0">
            <div class="media-left">
              <% if book.image.present? %>
                <%=  image_tag(book.image.variant(resize_to_limit: [30, 30]), alt: book.title ) %>
              <% elsif book.image_thumbnail.present? %>
                <%= image_tag(book.image_thumbnail, size: "30x30", alt: book.title) %>
              <% end %>
            </div>
            <div class="media-content">
              <p class="title is-6"><%= book.title %></p>
              <p class="subtitle is-6"><%= book.authors.map{ |author| author.name }.join(", ")%></p>
            </div>
          </div>
        </div>
        <%# Price %>
        <div class="has-text-right">
          <p class="book-price is-size-6 has-text-weight-bold">
            <% if book.sale_price.present? && book.is_on_sale %>
              <%= number_to_currency(book.sale_price, unit: "$") %>
            <% else %>
              <%= number_to_currency(book.price, unit: "$") %>
            <% end %>
          </p>
          <p>Quantity: <%= item["quantity"] %></p>
        </div>
      </div>
      <% unless index == @cart.length - 1 %>
        <hr class="my-4" style="height:1px;border-width:0;color:#bcbec6;background-color:#bcbec6">
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/components/_categories_side_bar.html.erb
<aside class="menu">
  <%= render partial: "layouts/components/filters" %>
  <p class="menu-label">
    Categories
  </p>
  <ul class="menu-list">
    <li><%= link_to "All books", root_path, class: ((current_page?(root_path) || (current_page?(books_path))) ? "is-active" : "")  %></li>
    <% @all_categories.each do |category| %>
      <li>
        <%= link_to "#{category.name.gsub("_", " ").gsub("-", ",")}", "/categories/#{category.name}", class: (current_page?("/categories/#{category.name}") ? "is-active" : "") %>
        <% #" (#{category.book_count})" %>
      </li>
    <% end %>
  </ul>
</aside>

app/views/layouts/components/_contact_form.html.erb
<h2 class="title has-text-info has-text-centered">Contact us </h2>
<form class= "p-3">
  <div class="field is-grouped">
    <div class="control is-expanded">
      <label class="label">First Name</label>
      <input class="input" type="text" placeholder="Enter your first name">
    </div>

    <div class="control is-expanded">
      <label class="label">Last Name</label>
      <input class="input" type="text" placeholder="Enter your last name">
    </div>
  </div>

  <div class="field is-grouped">
    <div class="control is-expanded">
      <label class="label">Email</label>
      <input class="input" type="email" placeholder="Enter your email">
    </div>
    <div class="control is-expanded">
      <label class="label">Phone</label>
      <input class="input" type="tel" placeholder="Enter your phone">
    </div>
  </div>
  <div class="field">
    <label class="label">Message</label>
    <div class="control">
      <textarea class="textarea" placeholder="Type your message"></textarea>
    </div>
  </div>

  <div class="field">
    <div class="control has-text-centered">
      <button class="button is-info">Send Message</button>
    </div>
  </div>
</form>

app/views/layouts/components/_contact_info.html.erb
<h2 class="title has-text-info has-text-centered">Join us </h2>

  <div class="columns p-3">
    <div class="column is-one-fifth">
      <div class="icon is-medium has-text-info">
        <i class="fas fa-2x pb-3 fa-regular fa-phone "></i>
      </div>
    </div>
    <div class="column">
        <p><%= @page.phone %></p>
    </div>
  </div>

    <div class="columns p-3">
    <div class="column is-one-fifth">
      <div class="icon is-medium has-text-info">
          <i class="fas fa-2x pb-3 fa-solid fa-envelope"></i>
      </div>
    </div>
    <div class="column">
      <p><%= @page.email %></p>
    </div>
  </div>


  <div class="columns p-3 ">
    <div class="column is-one-fifth">
      <div class="icon is-medium has-text-info">
        <i class="fas fa-2x pb-3 fa-solid fa-clock"></i>
      </div>
    </div>
    <div class="column">
        <p>Monday-Saturday 9am - 8pm, <br>Sunday - closed</p>
    </div>
  </div>

  <div class="columns p-3">
    <div class="column is-one-fifth">
      <div class="icon is-medium has-text-info">
        <i class="fas fa-2x pb-3 fa-solid fa-location-dot"></i>
      </div>
    </div>
    <div class="column">
      <p><%= @page.address %></p>
    </div>
  </div>

 <%# Social media links %>
  <div class="columns pl-6 pr-6 ">
    <div class ="column is-one-third  has-text-centered">
        <div class="icon is-medium has-text-info">
         <a href="https://twitter.com" target="_blank">
            <i class="fa-2x pb-3 fa-brands fa-twitter"></i>
          </a>
      </div>
    </div>

    <div class ="column is-one-third has-text-centered">
        <div class="icon is-medium has-text-info">
         <a href="https://facebook.com" target="_blank">
            <i class="fa-2x pb-3 fa-brands fa-facebook"></i>
          </a>
      </div>
    </div>

    <div class ="column is-one-third has-text-centered ">
        <div class="icon is-medium has-text-info">
          <a href="https://instagram.com" target="_blank">
            <i class="fa-2x pb-3 fa-brands fa-instagram"></i>
          </a>
      </div>
    </div>
  </div>

app/views/layouts/components/_filters.html.erb
<div class="mb-5">
  <p class="menu-label">Filters</p>
  <%= form_tag(request.path,  method: 'get', id: 'filter-form') do %>
    <ul class = "menu-list">
      <li class="field">
        <label class="checkbox">
          <%= check_box_tag :on_sale, 1, params[:on_sale].present?, class: 'filter-checkbox'%>
          <span class= "ml-1">On Sale</span>
        </label>
      </li>
      <li class="field">
        <label class="checkbox">
          <%= check_box_tag :new, 2, params[:new].present? , class: 'filter-checkbox'%>
          <span class= "ml-1"> New</span>
        </label>
      </li>
      <li class="field">
        <label class="checkbox">
          <%= check_box_tag :recently_updated, 1, params[:recently_updated].present?, class: 'filter-checkbox'%>
          <span class= "ml-1">Recently updated</span>
        </label>
      </li>
    </ul>
  <% end %>
</div>
<script>
  document.addEventListener("turbo:load", function() {
    const filterForm = document.getElementById('filter-form');
    const filterCheckboxes = document.querySelectorAll('.filter-checkbox');

    filterCheckboxes.forEach(checkbox => {
      checkbox.addEventListener('change', function() {
        filterForm.submit();
      });
    });
  });
</script>

app/views/layouts/components/_flash_messages.html.erb
<%# Devise flash messages %>
<% flash.each do |key, value| %>
  <div class="notification container mt-4 mb-0 <%= flash_class(key) %> is-light">
    <button class="delete"></button>
    <%= value %>
  </div>
<% end %>

app/views/layouts/components/_navbar.html.erb
<style>
  .logout-link {
    font-size: .875rem;
    background: none;
    border: none;
    cursor: pointer;
  }

  .logout-link:hover {
    background-color: #f5f5f5;
    color: #0a0a0a;
  }
</style>
<nav class="navbar is-light is-spaced has-shadow" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <%# Logo image %>
      <%= link_to root_path, class: "navbar-item" do %>
        <%= image_tag "bookhub_logo.svg", alt: "BookHub Logo" %>
      <% end %>
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start ml-4">
        <%= link_to "Home", root_path, class: "navbar-item" %>
        <%= link_to 'About', regular_page_path('about'), class: "navbar-item" %>
        <%= link_to 'Contact', regular_page_path('contact'), class: "navbar-item" %>
      </div>
      <div class="navbar-end">
        <%= render partial: "layouts/components/search_form" %>
        <div class="navbar-item">
          <div class="buttons">
            <%= link_to cart_path, class: "button is-link" do %>
              <span class="icon ml-1 mr-2" style="opacity: 0.8;">
                <i class="fa-solid fa-cart-shopping mr-0"></i>
              </span>
              <strong>Cart <span class="tag is-link is-light is-rounded ml-1"><%= @cart_item_count %></span></strong>
            <% end %>
          </div>
        </div>
        <div class ="navbar-item has-text-centered ">
          <% if current_user %>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                <%= current_user.username %>
              </a>
              <div class="navbar-dropdown is-right">
                <%= link_to "My Profile", edit_user_registration_path, class: "navbar-item" %>
                <%= link_to "My Orders", user_orders_path(current_user), class: "navbar-item" %>
                <hr class="navbar-divider">
                <%= form_with url: destroy_user_session_path, method: :delete, class: "logout-link navbar-item" do %>
                  <button type="submit" class="navbar-item has-text-left p-0" style="font-size: .875rem;background: none; border: none; cursor: pointer;">
                    <span class="icon">
                      <i class="fas fa-sign-out-alt"></i>
                    </span>
                    <span>Log out</span>
                  </button>
                <% end %>
              </div>
            </div>
          <% else %>
            <span class ="icon-text">
              <span class ="icon ">
                <i class="fa-solid fa-user fa-lg"></i>
              </span>
              <%= link_to "Log in", new_user_session_path,  class: "mr-2"%>
              <span> | </span>
              <%= link_to "Register", new_user_registration_path, class: "ml-2" %>
            </span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/components/_order_summary.html.erb
<div class="card mb-3">
  <div class="card-content">
    <p class="title is-5 mb-3">Order Summary</p>
    <% @book_orders.each do |book_order| %>
      <div class="is-flex is-justify-content-space-between">
        <div>
          <div class="media mb-0">
            <div class="media-left">
              <% if book_order.book.image.present? %>
                <%= image_tag(book_order.book.image.variant(resize_to_limit: [30, 30]), alt: book_order.book.title) %>
              <% elsif book_order.book.image_thumbnail.present? %>
                <%= image_tag(book_order.book.image_thumbnail, size: "30x30", alt: book_order.book.title) %>
              <% end %>
            </div>
            <div class="media-content">
              <p class="title is-6"><%= book_order.book.title %></p>
              <p class="subtitle is-6"><%= book_order.book.authors.map { |author| author.name }.join(", ") %></p>
            </div>
          </div>
        </div>
        <div class="has-text-right">
          <p class="book-price is-size-6 has-text-weight-bold">
              <%= number_to_currency(book_order.purchase_price, unit: "$") %>
          </p>
          <p>Quantity: <%= book_order.quantity %></p>
        </div>

      </div>
      <hr class="my-4" style="height:1px;border-width:0;color:#bcbec6;background-color:#bcbec6">
    <% end %>
  </div>
</div>

app/views/layouts/components/_order_total.html.erb
<div class="purchase-info-container p-4">
  <div class="is-flex is-justify-content-space-between is-align-items-baseline">
    <div class="is-size-6">Subtotal</div>
    <div class="is-size-6 has-text-weight-bold"><%= number_to_currency @order.subtotal, unit: "$" %></div>
  </div>
  <% if current_user.province %>
    <div class="is-flex is-justify-content-space-between is-align-items-baseline">
      <div class="is-size-6">GST (<%= number_to_percentage(current_user.province.gst * 100, precision: 0) %>)</div>
      <div class="is-size-6 has-text-weight-bold"><%= number_to_currency @order.subtotal * @order.purchase_gst, unit: "$" %></div>
    </div>
    <div class="is-flex is-justify-content-space-between is-align-items-baseline">
      <div class="is-size-6">PST (<%= number_to_percentage(current_user.province.pst * 100, precision: 0) %>)</div>
      <div class="is-size-6 has-text-weight-bold"><%= number_to_currency @order.subtotal * @order.purchase_pst, unit: "$" %></div>
    </div>
    <div class="is-flex is-justify-content-space-between is-align-items-baseline">
      <div class="is-size-6">HST (<%= number_to_percentage(current_user.province.hst * 100, precision: 0) %>)</div>
      <div class="is-size-6 has-text-weight-bold"><%= number_to_currency @order.subtotal * @order.purchase_hst, unit: "$" %></div>
    </div>
  <% end %>
  <div class="is-flex is-justify-content-space-between is-align-items-baseline">
    <div class="is-size-6">Shipping</div>
    <div class="is-size-6 has-text-weight-bold">FREE</div>
  </div>
  <hr class="my-4" style="height:1px;border-width:0;color:#bcbec6;background-color:#bcbec6">
  <div class="is-flex is-justify-content-space-between is-align-items-baseline">
    <div class="is-size-4">Total</div>
    <div class="is-size-4 has-text-danger-dark"><%= number_to_currency @order.subtotal * (1 + @order.purchase_gst + @order.purchase_pst+ @order.purchase_hst ) , unit: "$" %></div>
  </div>
</div>

app/views/layouts/components/_search_form.html.erb
<%= form_with(url: search_books_path, method: :get, local: true, class: "is-flex is-justify-content-flex-start") do %>
	<div class="field has-addons has-addons-right columns is-gapless">
	<p class="control column is-one-third">
		<span class="select">
			<%= select_tag :category_id,
				options_from_collection_for_select(
					Category.order(:name),
					:id,
					->(category) { category.name.gsub("_", " ").gsub("-", ",") },
					params[:category_id]), include_blank: "All categories", class: "select has-background-link-light" %>
		</span>
	</p>
	<p class="control column is-two-fifths">
		<%= text_field_tag(:keywords, nil, class: "input", placeholder: "Search by title or description") %>
	</p>
	<p class="control">
		<%= button_tag(class: "button is-info") do %>
			<i class="fas fa-search"></i>
		<% end %>
	</p>
	</div>
<% end %>

app/views/pages/show.html.erb
<section class="section">
  <div class="container box p-6">
    <h1 class="title pl-6"><%= @page.title %></h1>
    <div class="content subtitle mt-2 pl-6 ">
      <%= @page.content.html_safe %>
    </div>
    <% if @is_contact_page %>
      <div class="columns p-6 is-vcentered">
        <div class="column is-one-third box mr-6">
          <%= render partial: 'layouts/components/contact_info' %>
        </div>
        <div class="column box ml-6">
          <%= render partial: 'layouts/components/contact_form' %>
        </div>
      </div>
      <%= render partial: 'layouts/components/map' %>
    <% end %>
  </div>
</section>